// <auto-generated />
using System;
using Infrastructure.Persistence.EntityContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20221227181244_InitialSeed")]
    partial class InitialSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("ItemsDescription")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal?>("OrderCost")
                        .HasColumnType("money");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ItemsDescription = "Redmibook pro 14 Ryzen 5",
                            OrderCost = 155m,
                            OrderDate = new DateTime(2022, 12, 27, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "Ukraine, Lviv, Hazova 14",
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            ItemsDescription = "Samsung TV",
                            OrderCost = 1005m,
                            OrderDate = new DateTime(2022, 12, 25, 16, 5, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "Ukraine, Lviv, Naukova 14",
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 3,
                            ItemsDescription = "Christmas tree",
                            OrderCost = 537m,
                            OrderDate = new DateTime(2022, 12, 27, 10, 30, 33, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "Ukraine, Lviv, Horodotska 1",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Login" }, "UQ_user_login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DateOfBirth = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alex",
                            Gender = "M",
                            LastName = "Dane",
                            Login = "alex22",
                            Password = "$2a$11$PfkrgvNcDNvvQjht5z7xk.3QkggaRme5vNERKFAasDzuPtjfZx5oe"
                        },
                        new
                        {
                            UserId = 2,
                            DateOfBirth = new DateTime(2003, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sergiy",
                            Gender = "M",
                            LastName = "Vengrin",
                            Login = "sergiy19",
                            Password = "$2a$11$oOlmOVB8CuJ6v2t1VMRpmeJfhWwCDf05aMSGO9CJDYh9Ud34QaN0O"
                        },
                        new
                        {
                            UserId = 3,
                            DateOfBirth = new DateTime(2001, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "King",
                            Login = "john44",
                            Password = "$2a$11$oOlmOVB8Cud6v2t1VMRpmeJfhWwCDf05aMSGO9CJDYh9Ud34QaN0O"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
